name: UnitTest
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.202'

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Unit Test
        run: |
          mv gradle/wrapper/gradle-wrapper.properties.default gradle/wrapper/gradle-wrapper.properties
          mv gradle/allprojects.gradle.default gradle/allprojects.gradle
          ./gradlew clean test